'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.269
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("S_Bank.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1654120_571354482959002_880072910_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1654120_571354482959002_880072910_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3floppy_guardar_el_desmantelamiento_icono_4124_32__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3floppy-guardar-el-desmantelamiento-icono-4124-32 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Administracion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Administracion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Aha_Soft_Universal_Shop_Cash_register() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aha-Soft-Universal-Shop-Cash-register", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property anadir_mas_datos_de_base_icono_8363_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anadir-mas-datos-de-base-icono-8363-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property anadir_usuario_icono_7225_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anadir-usuario-icono-7225-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property editar_secuencias_de_comandos_icono_6203_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editar-secuencias-de-comandos-icono-6203-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fasticon_Shop_Cart_Shop_cart_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fasticon-Shop-Cart-Shop-cart-add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fasticon_Shop_Cart_Shop_cart_apply() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fasticon-Shop-Cart-Shop-cart-apply", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fasticon_Shop_Cart_Shop_cart_exclude() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fasticon-Shop-Cart-Shop-cart-exclude", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FondoAzul() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondoAzul", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FondoAzul2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondoAzul2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FondoRojo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondoRojo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imagesdfs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imagesdfs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property la_gente_de_negocios_de_usuario_icono_4645_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("la-gente-de-negocios-de-usuario-icono-4645-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property los_usuarios_de_raza_mixta_masculina_icono_4624_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("los-usuarios-de-raza-mixta-masculina-icono-4624-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MenuSplashBanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuSplashBanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MenuSplashBanco1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuSplashBanco1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pantalla_de_sistemas_de_utilidades_icono_4301_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pantalla-de-sistemas-de-utilidades-icono-4301-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property preocupaciones_icono_8798_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preocupaciones-icono-8798-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property preocupaciones_icono_8798_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preocupaciones-icono-8798-321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property puerta_icono_8827_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("puerta-icono-8827-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property salir_de_gnome_icono_8179_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salir-de-gnome-icono-8179-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stop_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stop 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tabla_de_madera_1280x800() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tabla_de_madera-1280x800", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tarjeta_de_informacion_del_usuario_icono_7370_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarjeta-de-informacion-del-usuario-icono-7370-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WallpaperAdmin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WallpaperAdmin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
